export default {
    // NAV_LIST:'NAV_LIST',
    // BANNER_LIST:'BANNER_LIST',
    // RECOMMENT_LIST:'RECOMMENT_LIST',
    CHANGE_CATEGORY:"CHANGE_CATEGORY",
    CHANGE_CONTENTS:"CHANGE_CONTENTS",
    GET_CLASSIFY_RECOMMEND:"GET_CLASSIFY_RECOMMEND",
    GET_CLASSIFY_OTHER:"GET_CLASSIFY_OTHER",
    ADD_CATEGORY:"ADD_CATEGORY",
    ADD_COURSE:"ADD_COURSE",
    GET_LESSON:"GET_LESSON",
    GET_ALLLESSON:"GET_ALLLESSON"
}
